services:
  seekserver:
    container_name: seekserver
    restart: always
    build: .
    networks:
      - proxyman_default
    # ports:
    #   - '7000:7000'
    # interactive shell
    # tty: true
    # stdin_open: true
    # command: /bin/bash

networks:
  proxyman_default:
    external: true
