services:
  seekserver:
    container_name: seekserver
    build: .
    restart: always
    networks:
      - proxyman_default
    # ports:
    #   - '5678:5678'

networks:
  proxyman_default:
    external: true
